### ISSUE TITLE
Commands dont work and folder doesnt load

### ISSUE THREAD

**Issue by HBHC1264** [ArvickC/PunchingSimulator#9]
[latest.log](https://github.com/ArvickC/PunchingSimulator/files/5627026/latest.log)

**Comment by ArvickC** [comment]
Vault Needed.

**Comment by HBHC1264** [comment]
i already have vault

**Comment by HBHC1264** [comment]
i mean i got it now. But nothing changed same error nothing works

**Comment by HBHC1264** [comment]
oh i need EssentailsX

**Comment by HBHC1264** [comment]
oooooof
